apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.ms.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.ms.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.ms.name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.ms.name }}-ms"
        imagePullPolicy: {{ .Values.containers.imagePullPolicy }}
        resources:
          requests:
            memory: {{ .Values.containers.resources.requests.memory }}        
          limits:
            memory: {{ .Values.containers.resources.limits.memory }}
        env:

        volumeMounts:
        - name: ms-logs-volume
          mountPath: /app/logs
        - name: app-{{ .Values.ms.name }}-volume
          mountPath: /deployments/config/app-{{ .Values.ms.name }}
        - name: ext-svc-{{ .Values.ms.name }}-volume
          mountPath: /deployments/config/ext-svc-{{ .Values.ms.name }}          

      volumes:
      - name: ms-logs-volume
        hostPath:
          path: "{{ .Values.CWD }}/{{ .Values.volumes.logs }}/{{ .Values.ms.name }}"
      - name: app-{{ .Values.ms.name }}-volume
        configMap:
          name: app-{{ .Values.ms.name }}
      - name: ext-svc-{{ .Values.ms.name }}-volume
        configMap:
          name: ext-svc-{{ .Values.ms.name }}
      - name: ms-exe-volume
        hostPath:
          path: "{{ .Values.CWD }}/{{ .Values.volumes.runtime }}"
