apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.ms.name }}-service"
spec:
  type: ClusterIP
  ports:
    - name: https
      protocol: TCP
      port: 8443
      targetPort: 8443
    - name: management
      protocol: TCP
      port: 8081
      targetPort: 8081

  selector:
    app: {{ .Values.ms.name }}