kind: "ConfigMap"
apiVersion: "v1"
metadata:
  name: ext-svc-{{ .Values.ms.name }}
data:
  application.yaml: |
    services:
      account-service:
        serviceUrl: 'http://account-service.default.svc.cluster.local:8443'
