apiVersion: v1
kind: PersistentVolume
metadata:
  name: couchbase-data-pv
spec:
  capacity:
    storage: {{ .Values.couchbase.data.capacity }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: {{ .Values.couchbase.data.path }}