apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: couchbase-data-pvc
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.couchbase.data.capacity }}