apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  type: LoadBalancer
  ports:
  - name: port-8091
    port: 8091
    targetPort: 8091
  - name: port-8092
    port: 8092
    targetPort: 8092
  - name: port-8093
    port: 8093
    targetPort: 8093
  - name: port-8094
    port: 8094
    targetPort: 8094
  - name: port-8095
    port: 8095
    targetPort: 8095
  - name: port-8096
    port: 8096
    targetPort: 8096
  - name: port-11210
    port: 11210
    targetPort: 11210
  - name: port-11211
    port: 11211
    targetPort: 11211
  selector:
    app: {{ .Release.Name }}