version: '3'

services:
  product-service:
    image: product-service-ms
    container_name: product-service-ms
    mem_limit: 1G
    ports:
      - "41234:8443"
    env_file:
      - ${ENV_VARS}/env_vars.txt
    environment:
      - "SPRING_CLOUD_STREAM_ENABLED=true"
      
    networks:
      - ms-net
    volumes:
      - ${MS_LOGS}/product-service-ms:/app/logs
      - ${MS_CONFIG}/product-service-ms.yaml:/app/core-ms.yaml
networks:
  ms-net:
    external: true
    name: ${MS_NET}