apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.ms.name }}-service"
spec:
  type: ClusterIP
  ports:
    {{- $ports := deepCopy .Values.ports }}
    {{- range $key, $port := $ports }}
    {{- if $port.enabled }}
  - name: {{ $key }}
    port: {{ $port.servicePort }}
    targetPort: {{ $port.containerPort }}
    protocol: {{ $port.protocol }}
    {{- end }}
    {{- end }}

  selector:
    app: {{ .Values.ms.name }}