kind: Service
apiVersion: v1
metadata:
  name: "{{ .Release.Name }}"
spec:
  selector:
    app: "{{ .Release.Name }}"
  type: NodePort
  ports:
  - protocol: TCP
    port: {{ .Values.containers.ports.svcPort }}
    targetPort: {{ .Values.containers.ports.containerPort }}
    nodePort: {{ .Values.containers.ports.nodePort }}