apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  type: LoadBalancer
  ports:
  - name: port-9092
    port: {{ .Values.kafka.ports.svcPort }}
    targetPort: {{ .Values.kafka.ports.containerPort }}   

  selector:
    app: {{ .Release.Name }}