{{- if .Values.zookeeper.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.zookeeper.serviceName }}
spec:
  type: LoadBalancer
  ports:
  - port: {{ .Values.zookeeper.ports.svcPort }}
    name: client
    targetPort: {{ .Values.zookeeper.ports.containerPort }}
  selector:
    app: zookeeper
{{- end }}